AllCops:
  Exclude:
    - 'spec/support/*'
    - 'bin/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Lint/UnifiedInteger:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": ()
    "%w": ()
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Security/MarshalLoad:
  Exclude:
    - 'lib/candy_check/play_store/discovery_repository.rb'
Style/SafeNavigation:
  Enabled: false
Style/DateTime:
  Enabled: false
